# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutline',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='大纲顺序'),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='title',
            field=models.CharField(max_length=128, verbose_name='大纲标题'),
        ),
    ]
